apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-helm-chart.fullname" . }}-configuration
data:
{{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
