apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
{{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
